disableStartupPopups: true
os:
  editPreset: 'nvim'
git:
  pagers:
    - externalDiffCommand: difft --color=always
gui:
  nerdFontsVersion: "3"
  showFileIcons: false
  filterMode: fuzzy
  mouseEvents: false
